module.exports = {
  LOGIN_SUCCESS: "login successful",
  PASSWORD_INCORRECT: "Sorry either entered e mail or Password is Incorrect",
  CLIENT_DOES_NOT_EXIST: "Sorry ! User does not exist",
  CLIENT_NOT_CREATED: "Some error occurred while creating the user.",
  INVALID_EMAIL: "Invalid email.",
  CLIENT_CREATED: "Congratulation ! User has been Created",
  ROLE_CONFLICT: "Sorry ! you are not authorised to perform this action contact super admin",
  CLIENTS_FOUND: "User list viewed successfully",
  CLIENT_IS_NOT_ACTIVE: "Sorry this user is inactive. Please contact Super Admin",
  CREATING_NOT_ALLOWED: "Creation of user is not allowed for this role",
  UPDATING_NOT_ALLOWED: "Updation of user is not allowed for this role",
  DELETION_NOT_ALLOWED: "Deletion of user is not allowed for this role",
  CONTACT_NO_EXIST: "Contact number already exists",
  NAME_EXIST: "name already exists",
  USER_NAME_EXIST: "user_name already exists",
  NO_PLAYERS: "No players exist",
  PLAYERS_FOUND: "Players found",
  NO_CLIENT_EXIST: "No user has been created by you yet",
  CLIENT_CANT_DELETED: "user cant get deleted",
  CLIENT_DELETED: "Congratulations! This user has been deleted",
  CLIENT_UPDATED: "Congratulations! This user  has been updated",
  CLIENT_NOT_UPDATED: "user could not get updated",
  PLAYER_CANT_LOGIN : "Sorry ! Players can not login into admin panel",
  NOT_PLAYER : "Sorry ! You are not a player",
  CANT_LOGIN : "Sorry ! You are not authorized to login here",
  NO_OTP : "Sorry ! There was no otp in database ",
  ENTER_REGISTERED_MOBILE_NUMBER : "Sorry ! Please Enter registered mobile number",
  OTP_EXPIRED : "Sorry ! Your otp has been expired",
  PROVIDE_PASSWORD : "Please enter password",
  PHNO_VERIFIED : "Your phone number has been verified",
  PASSWORD_EMPTY : "Enter password",
  countryList: "Country list",
  stateList: "State list",
  OTP_SEND: "OTP sent Successfully!",
  INCORRECT_OTP: "Incorrect OTP",
  BLOCK_BY_ADMIN: "You have been blocked by admin",
  UNBLOCK_BY_ADMIN: "You have been unblocked by admin",
  DELETE_BY_ADMIN: "Your account has been deleted by admin",
  NO_TOKEN: "Please provide token",
  LOGIN: "Login successfully",
  OTP_VERIFY: "OTP verified successfully",
  USER_ALREADY_EXIST: "User already exist",
  EMAIL_ALREADY_INUSE: "You already subscribe with this Email",
  USER_NOT_FOUND: "User not found",
  DATA_SAVED: "Data saved successfully.",
  SENDER_NOT_FOUND: "Sender not found.",
  RECEIVER_NOT_FOUND: "Receiver not found.",
  CATEGORY_NOT_FOUND: "Category not found",
  FEES_NOT_FOUND: "Fees not found",
  CATEGORY_ALREADY_EXIST: "Category  already exist",
  CATEGORY_UPDATED: "Category updated successfully",
  PROFILE_UPDATED: "Profile updated successfully",
  FEED_UPDATED: "Fees updated successfully",
  USER_EXISTS: "User Exists",
  MOBILE_EXIST: "This mobile number already exists",
  EMAIL_EXIST: "This email already exists",
  USER_DETAILS: "User details",
  USER_CREATED: "User created successfully",
  CATEGORY_CREATED: "Category created successfully",
  COURSE_CREATED: "Course created successfully",
  SUBCATEGORY_CREATED: "Subcategory created successfully",
  LANGUAGE_CREATED: "Language created successfully",
  FEES_CREATED: "Fees add successfully",
  USER_UPDATED: "User updated successfully",
  INCORRECT_LOGIN: "Incorrect login credential provided",
  INCORRECT_SOCIAL_USER:"User with social id exists, but the entered mobile number/email is incorrect",
  NOT_REGISTERED: "User not registered",
  NOT_ACTIVATED: "User not activated",
  RESET_LINK_SEND: "Reset password link has been sent at your email.",
  LINK_EXPIRED: "Password reset link has been expired",
  PWD_CHANGED: "Password has been changed successfully",
  PWD_NOT_MATCH: "Password not matched.",
  PWD_MATCHED: "Password matched.",
  CMS_SAVED: "Static content added successfully",
  FAQ_ADDED: "FAQ added successfully",
  UPLOAD_SUCCESS: "File uploaded successfully",
  TRANSACTION_SUCCESS: "Transaction has been completed",
  DETAILS_FETCHED: "Details has been fetched successfully.",
  DATA_FOUND: "Data found successfully",
  DATA_NOT_FOUND: "Data not found",
  UPDATE_SUCCESS: "Successfully updated",
  DELETE_SUCCESS: "Successfully deleted",
  USER_LOGOUT: "User logged out successfully",
  TWO_FA_GENERATED: "Two factor authentication url generated successfully.",
  INCORRECT_CODE: "Code expired, Please provide another one.",
  LIKED: "LIKE Succesfully",
  REPORTS_CREATED: "Reports created Succesfully",
  ACTIVITY_DETAILS: "Activity details",
  TRANSFER_DETAILS: "Transfer list",
  REPORTS_CREATED: "Reports created Succesfully",
  FEES_DETAILS: "Fees details found Succesfully",
  DATA_EXIST: "This data already exists",
  FOLLOW: "YOu have successfully following this user.",
  UNFOLLOW: "YOu have successfully unfollowing this user.",
  FOLOWERS_LIST: "Followers list",
  UNFOLOWING: "Unfollowing Success",
  SUBSCRIPTION_ADDED: "Subscription plan added successfully.",
  FILE_NOT_FOUND: "Random file not found.",
  METADATA_UPLOADED: "Successfully uploaded and transferred.",
  UNSUBSCRIBED: "You have successfully unsubscribed.",
  MODERATOR_ADDED: "Moderator added successfully.",
  SHARED_AUDIENCE: "Successfully shared with audience.",
  LIKES: "Added to liked nfts.",
  DISLIKES: "Removed from liked nfts.",
  LIKE_FEED: "Added to liked feed.",
  DISLIKE_FEED: "Removed from liked feed.",
  FEED_NOT_FOUND: "Feed not found.",
  REPORT_NOT_ALLOWED:
    "You are not allowed to share the report as you are blocked by Admin.",
  CHAT_NOT_FOUND: "Chat not found.",
  REPORTED: "You have successfully reported.",
  ALREADY_REPORTED: "You have already reported for this chat.",
  BLOCKED: "Successfully blocked.",
  WARNING_SENT: "Successfully sent.",
  STOPPED: "Auction has been stopped successfully.",
  SUBSCRIPTION_NOT_FOUND: "Subscription not found.",
  PLAN_ADDED: "You have successfully selected the plan.",
  MAIL_SEND: "Mail Send successfully. ",
  UNAUTHORIZED: "Unauthorized person.",
  ALREADY_REQUESTED: "Request already send",
  PROJECT_REQUEST: "Request send successfully",
  REQUEST_REJECTED: "Request reject successfully",
  REQUEST_APPROVED: "Request approve successfully",
  ALREADY_EXIST: "already in database",
  INCORRECT_VALUE: "password and confirmPassword should be same",
  CATEGORY_ADDED: "Category added successfully.",
  SUBCATEGORY_ADDED: "subcategory added successfully.",
  CONTACT_US: "Thanks! We have receive your message.",
  ALREADY_SUBSCRIBE: "You already subscribe with this email",
  SUBSCRIBE_SUCCESS: "Thanks to subscribe for updates and announcements.",
  RESET_SUCCESS: "Password reset Successfully.",
  ACTIVE_SUCCESS: "Active Successfully",
  DEACTIVE_SUCCESS: "Deactive Successfully",
  ALREADY_USED: "This id is already in use.",
  FB_LINKED: "Id has been linked successfully with fb.",
  ONLINE: "You are online now.",
  OFFLINE: "You are offline now.",
  CREATED_ROOM: "Room code has been created successfully.",
  SHARED_CODE: "Room code has been shared successfully.",
  ALREADY_JOINED: "You have already joined this game room.",
  ROOM_NOT_FOUND: "You haven't created any room, please create first.",
  INSUFFICIENT_FUND: "You don't have sufficient funds to join this room.",
  ROOM_EXCEEDED: "Room limit exceeded.",
  JOINED_ROOM: "Game room has been joined successfully.",
  LEAVE_SUCCESS: "You have left successfully this game.",
  ALREADY_COMPLETED: "This game room is already completed.",
  GAME_STARTED: "Game has been started successfully.",
  ROLLED_SUCCESS: "Dice rolled successfully.",
  STONE_SUCCESS: "Stone moved successfully.",
  ADD_ADVERT: "Advertisment added successfully.",
  UPDATE_ADVERT: "Advertisment updated successfully.",
  STATUS_CHANGED: "Advertisment status visiblity changed successfully",
  NOT_AVAILABLE_SPIN: "You don't have any spin free available.",
  FIRST_PAY: "You don't have any payment for spin wheel.",
  SUCCESS_SPIN: "Successfully done.",
  GUEST_NOT_FOUND: "Invalid guest id.",
  PAID_SUCCESS: "Spin fee paid successfully.",
  SPIN_NOT_FOUND: "Spin not found.",

  ALREADY_EXITS: "Data already exits.",
  COURSE_ALREADY_EXITS: "Course already exist",
  CATEGORY_ALREADY_EXITS: "Course already exist",
  SUBCATEGORY_ALREADY_EXITS: "Course already exist",
};
